name: Azure Login

on:
  workflow_dispatch:

jobs:
  job1: 
    runs-on: self-hosted
    steps:
      - name: Login to Azure
        uses: hyperskill/azure-login@v3.0.0
        with:
          client_id: 
          client_secret:
          subscription_id:
          tenant_id: 
