name: ci_1

on:
  workflow_dispatch: 

jobs:
   build:
     runs-on: ubuntu-latest
     
     steps:
      - name: Build
        run: |
          echo "Building.."
     
      - name: Use LAB SECRET
        run: |
          echo "Lab Secret is ${{ secrets.LAB_SECRET }}"