name: ci_1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "select environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
   config:
     runs-on: ubuntu-latest
     
     steps:
      - name: Show select Environment
        run: |
          echo "Selected Environment ${{ inputs.environment }}"

  production:
    if: ${{ inputs.environment == "prod" }}
    runs-on: ubuntu-latest

    steps:
      - name: Production Deployment
        run: |
          echo "Running Production job ${{ github.run_number }}"

  