name: Environment Lab

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: prod

    steps:
      - name: Show Environment configuration
        run: |
          echo "GitHub Environment: prod"
          echo "Deploy Target: ${{ vars.DEPLOY_TARGET }}"