name: Permissions Lab

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  test-permissions:
    runs-on: ubuntu-latest

    steps:
      - name: Show token
        run: |
          echo "Token avaiable: ${{ github.token != '' }}"
          echo "HELLO"