name: Permissions Lab

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull_requests: none

    steps:
      - name: Read pull_requests
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/pulls
          | jq -r '
              ["NUMBER", "TITLE", "STATE", "AUTHOR"],
              (.[] | [.number, .title, .state, .user.login])
              | @tsv
            ' | column -t -s $'\t'