name: PR CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pre-check:
    runs-on: ubuntu-latest

    steps:
      - name: PR check
        run: |
          echo "Running PR CI"
          exit 1