name: PR Fail CI

on:
  workflow_dispatch:

jobs:
  pre-check:
    runs-on: ubuntu-latest

    steps:
      - name: codeowners test
        run: |
          echo "Running PR CI"
          echo "testing codeowners"
