name: PR Security Lab

on:
  pull_request_target:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Show Event Information
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"