name: Reusable ci

on:
  workflow_call:
    inputs:
      reusable_environment:
        description: "Environment to run against"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - id: run_reusable_workflow
      run: |
        echo "this job came from reusable workflow"
        echo " Environment: ${{ inputs.reusable_environment }}"