# name: Azure Login
#  on:
#   workflow_dispatch:

# jobs:
#   job1:
#     runs-on: self-hosted
#     steps:
#       - name: Login to Azure
#         uses: hyperskill/azure-login@v3.0.0
#         with:
#           client_id: "3e761f2f-a81a-422d-8e8c-8d790b6680ac"
#           client_secret: "Jl.8Q~5drVEWW1ypKUXEYjk_3HVdPzPq76uexbnb"
#           subscription_id: "f404697e-6425-41fa-99cd-804885e9a8d5"
#           tenant_id: "aee24866-30ec-48a2-bcb3-dcec25f7b031"
  
#       - uses: actions/checkout@v4
#       - name: init
#         run: terraform init
#       - name: plan
#         run: terraform plan -out=plan
#       - name: plan
#         run: terraform apply --auto-approve plan
